r"""Multiscale operator decompositions for physically ordered RF windows.

The ambient vectorization is NumPy row-major: a ``K x T`` coefficient matrix
is identified with ``C^K \otimes C^T`` and an operator is indexed as
``P[k, t, l, s]`` after reshaping to ``(K, T, K, T)``.

Two different group averages are deliberately kept separate:

* block-unitary twirling mixes window coordinates and retains only averaged
  per-block marginals;
* block-phase twirling preserves every operator block whose two window
  indices belong to the same interval block.  Its filtration differences are
  the cross-window coherence bands used by Track C2.

The difference of two nested block-phase expectations is an orthogonal
projection in Hilbert--Schmidt operator space.  It need not be a positive or
completely positive map, so this module never describes a band projection as
a conditional expectation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np
from numpy.typing import NDArray

from .mechanism import coefficient_matrices, hermitian_hs_coordinates


Partition = tuple[tuple[int, ...], ...]


@dataclass(frozen=True)
class TreeHaarMode:
    """One weighted Haar contrast generated by a binary interval split."""

    level: int
    parent: tuple[int, ...]
    left: tuple[int, ...]
    right: tuple[int, ...]
    vector: NDArray[np.float64]


def balanced_interval_partitions(window_count: int) -> tuple[Partition, ...]:
    """Return a deterministic coarse-to-fine binary interval filtration.

    Every non-singleton block is split at its integer midpoint.  This also
    handles non-dyadic window counts; for example, seven windows produce an
    unbalanced but complete binary tree and a weighted orthonormal Haar basis.
    """

    if int(window_count) != window_count or window_count <= 0:
        raise ValueError("window_count must be a positive integer")
    current: Partition = (tuple(range(int(window_count))),)
    output = [current]
    while any(len(block) > 1 for block in current):
        refined: list[tuple[int, ...]] = []
        for block in current:
            if len(block) == 1:
                refined.append(block)
                continue
            # Put the unmatched element in the earlier physical interval.  In
            # particular, T=7 freezes as 1234|567 then 12|34|56|7.
            midpoint = (len(block) + 1) // 2
            refined.extend((block[:midpoint], block[midpoint:]))
        current = tuple(refined)
        output.append(current)
    return tuple(output)


def validate_partition_chain(
    partitions: Sequence[Sequence[Sequence[int]]], *, window_count: int
) -> tuple[Partition, ...]:
    """Validate and canonicalize a nested coarse-to-fine partition chain."""

    if window_count <= 0 or not partitions:
        raise ValueError("a positive window count and a nonempty chain are required")
    canonical: list[Partition] = []
    universe = tuple(range(int(window_count)))
    for level, partition in enumerate(partitions):
        blocks = tuple(tuple(int(value) for value in block) for block in partition)
        flattened = tuple(value for block in blocks for value in block)
        if any(not block for block in blocks):
            raise ValueError(f"empty block at level {level}")
        if flattened != universe or len(set(flattened)) != window_count:
            raise ValueError(f"level {level} is not a partition of all windows")
        if any(tuple(sorted(block)) != block for block in blocks):
            raise ValueError(f"level {level} blocks must be ordered")
        canonical.append(blocks)
    if canonical[0] != (universe,):
        raise ValueError("the chain must start with the indiscrete partition")
    if canonical[-1] != tuple((value,) for value in universe):
        raise ValueError("the chain must end with the singleton partition")
    for level in range(1, len(canonical)):
        previous = canonical[level - 1]
        owner = {
            value: block_index
            for block_index, block in enumerate(previous)
            for value in block
        }
        for block in canonical[level]:
            if len({owner[value] for value in block}) != 1:
                raise ValueError(f"level {level} is not a refinement")
    return tuple(canonical)


def _chain_or_default(
    window_count: int,
    partitions: Sequence[Sequence[Sequence[int]]] | None,
) -> tuple[Partition, ...]:
    chain = (
        balanced_interval_partitions(window_count)
        if partitions is None
        else partitions
    )
    return validate_partition_chain(chain, window_count=window_count)


def _operator_blocks(
    operator: Any, *, matrix_rows: int, window_count: int
) -> NDArray[np.complex128]:
    values = np.asarray(operator, dtype=np.complex128)
    dimension = int(matrix_rows) * int(window_count)
    if values.shape != (dimension, dimension):
        raise ValueError("operator shape does not match matrix_rows * window_count")
    return values.reshape(matrix_rows, window_count, matrix_rows, window_count)


def _partition_mask(partition: Partition, window_count: int) -> NDArray[np.bool_]:
    owner = np.empty(window_count, dtype=np.int64)
    for block_index, block in enumerate(partition):
        owner[np.asarray(block, dtype=np.int64)] = block_index
    return owner[:, None] == owner[None, :]


def phase_conditional_expectation(
    operator: Any,
    partition: Sequence[Sequence[int]],
    *,
    matrix_rows: int,
    window_count: int,
) -> NDArray[np.complex128]:
    r"""Average over phases constant on each partition block.

    The output retains ``P[k,t,l,s]`` exactly when ``t`` and ``s`` lie in the
    same block.  This map is positive, trace preserving, idempotent, and
    Hilbert--Schmidt self-adjoint.
    """

    # A standalone partition need not itself include the coarse and singleton
    # endpoints required of a full filtration, so validate it directly.
    blocks = tuple(tuple(int(value) for value in block) for block in partition)
    flattened = tuple(value for block in blocks for value in block)
    if (
        any(not block for block in blocks)
        or flattened != tuple(range(window_count))
        or len(set(flattened)) != window_count
    ):
        raise ValueError("partition must contain every window exactly once")
    values = _operator_blocks(
        operator, matrix_rows=matrix_rows, window_count=window_count
    )
    mask = _partition_mask(blocks, window_count)
    output = np.where(mask[None, :, None, :], values, 0.0)
    return np.asarray(output.reshape(values.shape[0] * window_count, -1))


def block_unitary_conditional_expectation(
    operator: Any,
    partition: Sequence[Sequence[int]],
    *,
    matrix_rows: int,
    window_count: int,
) -> NDArray[np.complex128]:
    r"""Reference twirl under independent full unitary mixing in each block.

    For a block ``B``, all cross-window blocks vanish and every diagonal block
    becomes ``|B|^{-1} sum_{u in B} P[u,u]``.  This valid construction is a
    marginal-mixing scale, not a cross-window coherence scale.
    """

    blocks = tuple(tuple(int(value) for value in block) for block in partition)
    flattened = tuple(value for block in blocks for value in block)
    if (
        any(not block for block in blocks)
        or flattened != tuple(range(window_count))
        or len(set(flattened)) != window_count
    ):
        raise ValueError("partition must contain every window exactly once")
    values = _operator_blocks(
        operator, matrix_rows=matrix_rows, window_count=window_count
    )
    output = np.zeros_like(values)
    for block in blocks:
        average = sum(values[:, t, :, t] for t in block) / float(len(block))
        for t in block:
            output[:, t, :, t] = average
    return np.asarray(output.reshape(matrix_rows * window_count, -1))


def tree_haar_modes(
    window_count: int,
    partitions: Sequence[Sequence[Sequence[int]]] | None = None,
) -> tuple[TreeHaarMode, ...]:
    """Return the weighted real Haar contrasts induced by a binary chain."""

    chain = _chain_or_default(window_count, partitions)
    modes: list[TreeHaarMode] = []
    for level in range(1, len(chain)):
        previous = chain[level - 1]
        current = chain[level]
        for parent in previous:
            children = tuple(block for block in current if set(block).issubset(parent))
            if children == (parent,):
                continue
            if len(children) != 2 or tuple(value for child in children for value in child) != parent:
                raise ValueError("tree Haar construction requires binary ordered splits")
            left, right = children
            a = float(len(left))
            b = float(len(right))
            total = a + b
            vector = np.zeros(window_count, dtype=np.float64)
            vector[np.asarray(left, dtype=np.int64)] = np.sqrt(b / (a * total))
            vector[np.asarray(right, dtype=np.int64)] = -np.sqrt(a / (b * total))
            vector.setflags(write=False)
            modes.append(
                TreeHaarMode(
                    level=level,
                    parent=parent,
                    left=left,
                    right=right,
                    vector=vector,
                )
            )
    if len(modes) != window_count - 1:
        raise ValueError("a complete binary chain must generate T-1 Haar modes")
    basis = np.column_stack(
        (np.ones(window_count, dtype=np.float64) / np.sqrt(window_count),)
        + tuple(mode.vector for mode in modes)
    )
    if not np.allclose(basis.T @ basis, np.eye(window_count), atol=2.0e-14):
        raise RuntimeError("weighted tree Haar basis is not orthonormal")
    return tuple(modes)


def marginal_mode_component(
    operator: Any,
    mode: Any,
    *,
    matrix_rows: int,
    window_count: int,
) -> NDArray[np.complex128]:
    """Project the diagonal window-block field onto one real mode."""

    vector = np.asarray(mode, dtype=np.float64)
    if vector.shape != (window_count,):
        raise ValueError("mode must have one real coefficient per window")
    if not np.isclose(float(vector @ vector), 1.0, atol=2.0e-13):
        raise ValueError("mode must have unit Euclidean norm")
    values = _operator_blocks(
        operator, matrix_rows=matrix_rows, window_count=window_count
    )
    coefficient = sum(vector[t] * values[:, t, :, t] for t in range(window_count))
    output = np.zeros_like(values)
    for t in range(window_count):
        output[:, t, :, t] = vector[t] * coefficient
    return np.asarray(output.reshape(matrix_rows * window_count, -1))


def multiscale_operator_components(
    operator: Any,
    *,
    matrix_rows: int,
    window_count: int,
    partitions: Sequence[Sequence[Sequence[int]]] | None = None,
) -> dict[str, Any]:
    """Return the exact orthogonal parallel/marginal/coherence decomposition."""

    chain = _chain_or_default(window_count, partitions)
    expectations = tuple(
        phase_conditional_expectation(
            operator,
            partition,
            matrix_rows=matrix_rows,
            window_count=window_count,
        )
        for partition in chain
    )
    coherence = {
        f"level_{level}": expectations[level - 1] - expectations[level]
        for level in range(1, len(expectations))
    }
    constant = np.ones(window_count, dtype=np.float64) / np.sqrt(window_count)
    parallel = marginal_mode_component(
        operator,
        constant,
        matrix_rows=matrix_rows,
        window_count=window_count,
    )
    marginal: dict[str, list[NDArray[np.complex128]]] = {}
    modes = tree_haar_modes(window_count, chain)
    for mode in modes:
        marginal.setdefault(f"level_{mode.level}", []).append(
            marginal_mode_component(
                operator,
                mode.vector,
                matrix_rows=matrix_rows,
                window_count=window_count,
            )
        )
    reconstructed = parallel.copy()
    for components in marginal.values():
        for component in components:
            reconstructed += component
    for component in coherence.values():
        reconstructed += component
    return {
        "partitions": chain,
        "phase_expectations": expectations,
        "parallel": parallel,
        "marginal": {key: tuple(value) for key, value in marginal.items()},
        "coherence": coherence,
        "haar_modes": modes,
        "reconstructed": reconstructed,
    }


def _phase_kernel(
    same_window_inner: NDArray[np.complex128], partition: Partition
) -> NDArray[np.float64]:
    output = np.zeros(same_window_inner.shape[:2], dtype=np.float64)
    for block in partition:
        summed = np.sum(same_window_inner[:, :, np.asarray(block)], axis=2)
        output += np.abs(summed) ** 2
    return output


def _marginal_coordinates(
    matrices: NDArray[np.complex128], mode: NDArray[np.float64]
) -> NDArray[np.float64]:
    operators = np.einsum(
        "t,nkt,nlt->nkl", mode, matrices, matrices.conj(), optimize=True
    )
    return np.asarray(hermitian_hs_coordinates(operators), dtype=np.float64)


def multiscale_projective_kernel_blocks(
    first: Any,
    second: Any | None = None,
    *,
    matrix_rows: int,
    partitions: Sequence[Sequence[Sequence[int]]] | None = None,
) -> dict[str, Any]:
    """Compute exact kernels for every orthogonal Track C2 operator band."""

    left = coefficient_matrices(first, matrix_rows=matrix_rows)
    right = left if second is None else coefficient_matrices(second, matrix_rows=matrix_rows)
    if left.shape[1:] != right.shape[1:]:
        raise ValueError("kernel inputs must share their K x T shape")
    window_count = left.shape[2]
    chain = _chain_or_default(window_count, partitions)
    same_window_inner = np.einsum(
        "nkt,mkt->nmt", left.conj(), right, optimize=True
    )
    phase_kernels = tuple(_phase_kernel(same_window_inner, item) for item in chain)
    coherence = {
        f"level_{level}": np.asarray(
            phase_kernels[level - 1] - phase_kernels[level], dtype=np.float64
        )
        for level in range(1, len(chain))
    }
    constant = np.ones(window_count, dtype=np.float64) / np.sqrt(window_count)
    left_constant = _marginal_coordinates(left, constant)
    right_constant = (
        left_constant if second is None else _marginal_coordinates(right, constant)
    )
    parallel = left_constant @ right_constant.T
    marginal: dict[str, NDArray[np.float64]] = {}
    for mode in tree_haar_modes(window_count, chain):
        key = f"level_{mode.level}"
        left_coordinates = _marginal_coordinates(left, mode.vector)
        right_coordinates = (
            left_coordinates
            if second is None
            else _marginal_coordinates(right, mode.vector)
        )
        contribution = left_coordinates @ right_coordinates.T
        marginal[key] = marginal.get(key, np.zeros_like(contribution)) + contribution
    exact = np.abs(
        left.reshape(left.shape[0], -1) @ right.reshape(right.shape[0], -1).conj().T
    ) ** 2
    reconstructed = parallel.copy()
    for contribution in marginal.values():
        reconstructed += contribution
    for contribution in coherence.values():
        reconstructed += contribution
    return {
        "partitions": chain,
        "exact": np.asarray(exact.real, dtype=np.float64),
        "parallel": np.asarray(parallel.real, dtype=np.float64),
        "marginal": marginal,
        "coherence": coherence,
        "reconstructed": np.asarray(reconstructed.real, dtype=np.float64),
        "residual": np.asarray((exact - reconstructed).real, dtype=np.float64),
    }


def center_kernel(kernel: Any) -> NDArray[np.float64]:
    """Double-center a square real kernel without constructing the centering matrix."""

    values = np.asarray(kernel, dtype=np.float64)
    if values.ndim != 2 or values.shape[0] != values.shape[1]:
        raise ValueError("kernel must be square")
    row_mean = np.mean(values, axis=1, keepdims=True)
    return values - row_mean - row_mean.T + float(np.mean(values))


def centered_kernel_alignment(first: Any, second: Any) -> float:
    """Return the Frobenius cosine of two centered kernel matrices."""

    left = center_kernel(first)
    right = center_kernel(second)
    denominator = float(np.linalg.norm(left) * np.linalg.norm(right))
    if denominator <= np.finfo(np.float64).tiny:
        return 0.0
    return float(np.sum(left * right) / denominator)


def kernel_effective_rank(kernel: Any, *, relative_tolerance: float = 1.0e-10) -> float:
    """Return the participation-ratio rank of a centered PSD kernel."""

    centered = center_kernel(kernel)
    eigenvalues = np.linalg.eigvalsh(0.5 * (centered + centered.T))
    scale = max(1.0, float(np.max(np.abs(eigenvalues))))
    retained = np.maximum(eigenvalues[eigenvalues > relative_tolerance * scale], 0.0)
    if retained.size == 0:
        return 0.0
    return float(np.sum(retained) ** 2 / np.sum(retained**2))


def kernel_subspace_overlap(
    first: Any,
    second: Any,
    *,
    energy_fraction: float = 0.95,
    relative_tolerance: float = 1.0e-10,
) -> dict[str, float | int]:
    """Compare dominant centered-kernel subspaces using robust overlaps.

    The returned operator overlap is the largest squared canonical
    correlation, the Frobenius overlap is their mean after zero-padding to the
    smaller rank, and ``q95_overlap`` is the empirical 0.95 quantile.  No
    infimum/principal-angle minimum is used.
    """

    if not 0.0 < energy_fraction <= 1.0:
        raise ValueError("energy_fraction must lie in (0, 1]")

    def dominant(kernel: Any) -> NDArray[np.float64]:
        centered = center_kernel(kernel)
        values, vectors = np.linalg.eigh(0.5 * (centered + centered.T))
        order = np.argsort(values)[::-1]
        values = values[order]
        vectors = vectors[:, order]
        scale = max(1.0, float(np.max(np.abs(values))))
        positive = values > relative_tolerance * scale
        values = values[positive]
        vectors = vectors[:, positive]
        if values.size == 0:
            return np.zeros((centered.shape[0], 0), dtype=np.float64)
        cutoff = int(np.searchsorted(np.cumsum(values), energy_fraction * np.sum(values)) + 1)
        return vectors[:, :cutoff]

    left = dominant(first)
    right = dominant(second)
    if left.shape[1] == 0 or right.shape[1] == 0:
        return {
            "left_rank": int(left.shape[1]),
            "right_rank": int(right.shape[1]),
            "operator_overlap": 0.0,
            "frobenius_overlap": 0.0,
            "q95_overlap": 0.0,
        }
    squared = np.linalg.svd(left.T @ right, compute_uv=False) ** 2
    return {
        "left_rank": int(left.shape[1]),
        "right_rank": int(right.shape[1]),
        "operator_overlap": float(np.max(squared)),
        "frobenius_overlap": float(np.sum(squared) / min(left.shape[1], right.shape[1])),
        "q95_overlap": float(np.quantile(squared, 0.95)),
    }
